name: host-port-checker-prod
services:
  host-port-checker-prod:
    type: snstateless
    image: eu.gcr.io/halfpipe-io/ee-host-port-checker:${BUILD_VERSION}
    ports:
      - name: web
        containerPort: 3000
        servicePort: 3000
        protocol: http
    snprobe:
      healthcheckProbe:
        httpGet:
          path: /
          port: 3000
    sningress:
      routes:
        - route: host-port-checker.apps.private.k8s.springernature.io
          cname: katee-host-port-checker.ee.springernature.io
          servicePort: 3000
