apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: host-port-checker-dev
spec:
  components:
  - name: host-port-checker-dev
    type: snstateless
    properties:
      image: eu.gcr.io/halfpipe-io/ee-host-port-checker:${BUILD_VERSION}
      ports:
      - name: web
        containerPort: 3000
        servicePort: 3000
        protocol: http
    traits:
    - type: sningress
      properties:
        privateRoutes:
        - route: host-port-checker.apps.private.k8s-dev.springernature.io
          servicePort: 3000
    - type: snprobe
      properties:
        livenessProbe:
          httpGet:
            path: /
            port: 3000
